### PR TITLE
resolve the tailwindcss path based on the open file path

### LINKED ISSUE #29: LSP-tailwindcss doesn't work after updating npm dependencies
Hi,
my lsp-tailwindcss stopped working after updating my dependencies. Any advice?

`package.json (truncated)`
```
{
  "devDependencies": {
    "@tailwindcss/aspect-ratio": "^0.4.0",
    "@tailwindcss/forms": "^0.4.0",
    "@tailwindcss/line-clamp": "^0.3.0",
    "@tailwindcss/typography": "^0.5.0",
    "@types/tailwindcss": "^2.2.4",
    "tailwindcss": "^3.0.0"
  }
}
```

# Troubleshooting: LSP-tailwindcss
## Version
 - LSP: 1.14.0
 - Sublime Text: 4121
## Server Test Run
 - exit code: -1
 - output
```
neither "command" nor "tcp_port" is provided; cannot start a language server
```
## Server Configuration
 - command
```json
[]
```
 - shell command
```sh

```
 - selector
```
(text.html.basic)|(embedding.php)|(embedding.php)|(source.js)|(source.css)|(source.scss)
```
 - priority_selector
```
(text.html.basic)|(embedding.php)|(text.blade)|(text.html.twig)|(source.jsx)|(source.js.react)|(source.js)|(source.css)|(source.tsx)|(source.ts)|(source.scss)|(source.less)|(text.html.vue)|(text.html.svelte)
```
 - init_options
```json
{}
```
 - settings
```json
{
  "tailwindCSS": {
    "classAttributes": [
      "class", 
      "className", 
      "ngClass"
    ], 
    "colorDecorators": true, 
    "emmetCompletions": false, 
    "experimental": {
      "classRegex": []
    }, 
    "includeLanguages": {}, 
    "lint": {
      "cssConflict": "warning", 
      "invalidApply": "error", 
      "invalidConfigPath": "error", 
      "invalidScreen": "error", 
      "invalidTailwindDirective": "error", 
      "invalidVariant": "error", 
      "recommendedVariantOrder": "warning"
    }, 
    "rootFontSize": 16, 
    "showPixelEquivalents": true, 
    "validate": true
  }
}
```
 - env
```json
{
  "PATH": "/usr/bin:"
}
```

## Active view
 - File name
```
/home/pc-5002/code/project-root-5/aureliajs/src/resources/elements/au-header.html
```
 - Settings
```json
{
  "auto_complete_selector": "meta.tag, text.html, source - comment - string.quoted.double.block - string.quoted.single.block - string.unquoted.heredoc", 
  "lsp_active": true, 
  "syntax": "Packages/HTML/HTML.sublime-syntax"
}
```
 - base scope
```
text.html.basic
```

## Project / Workspace
 - folders
```json
[
  "/home/pc-5002/code/project-root-5/aureliajs", 
  "/home/pc-5002/code/project-root-5"
]
```
 - is project: True
 - project data:
```json
{
  "folders": [
    {
      "folder_exclude_patterns": [
        "node_modules", 
        "scripts"
      ], 
      "follow_symlinks": true, 
      "name": "main", 
      "path": "aureliajs"
    }, 
    {
      "folder_exclude_patterns": [
        ".svn", 
        ".git", 
        ".hg", 
        "CVS", 
        "aureliajs"
      ], 
      "follow_symlinks": true, 
      "name": "root", 
      "path": "."
    }
  ], 
  "settings": {
    "lsp_code_actions_on_save": {
      "source.fixAll.eslint": true, 
      "source.fixAll.stylelint": true
    }, 
    "LSP-tailwindcss": {
      "languages": [
        {
          "languageId": "html", 
          "scopes": [
            "text.html.basic"
          ], 
          "syntaxes": [
            "Packages/HTML/HTML.sublime-syntax"
          ]
        }, 
        {
          "languageId": "css", 
          "scopes": [
            "source.css", 
            "source.css.tailwind"
          ], 
          "syntaxes": [
            "Packages/CSS/CSS.sublime-syntax", 
            "Packages/Tailwind CSS/Tailwind CSS.sublime-syntax"
          ]
        }
      ], 
      "settings": {
        "tailwindCSS.emmetCompletions": true
      }
    }, 
    "LSP-eslint": {
      /* ... */
    }, 
    "LSP-stylelint": {
      /* ... */
    }, 
    "LSP-typescript": {
      /* ... */
    }, 
    "tailwindcss-Class-Sorter": {
      /* ... */
    }, 
    "detect_indentation": false, 
    "show_definitions": false, 
    "show_line_endings": true, 
    "use_tab_stops": true, 
    "word_wrap": true
  }
}
```

## LSP configuration

```json
{}
```
## System PATH
 - /home/pc-5002/.local/bin
 - /usr/local/bin
 - /usr/bin
 - /bin
 - /usr/local/sbin
 - /usr/lib/jvm/default/bin
 - /usr/bin/site_perl
 - /usr/bin/vendor_perl
 - /usr/bin/core_perl
 - /var/lib/snapd/snap/bin

### PR DESCRIPTION
**Pull request by predragnikolic**
closes #29

### CODE REVIEW

**Comment by rchl** [comment]
It really doesn't feel right to do that. The user should instead ensure that he's opening the root folder.
This will just produce random results depending on what file is opened first.

Many servers require specific structure and i don't think we should be trying to fixup things like that.

**Comment by predragnikolic** [comment]
Each time you write a comment, it forces me to start questioning my actions :D

Reasons why I would consider merging this:
1. For the user it would be better if this works without them having to care if it is the root folder.
2. The tailwindcss extension for VS code support starting the tailwindcss ls even when the node_modules is not at the root. 


Reasons why I would against merging this:
> This will just produce random results depending on what file is opened first.

Yes, I have the same concern.

**Comment by predragnikolic** [comment]
> This will just produce random results depending on what file is opened first.

What if the user opens a ts file in the root folder, 
but the node_modules folder is nested somewhere bellow".... so yeah... we will still have this problem...

**Comment by predragnikolic** [comment]
This PR is not the correct fix.

**Comment by davidwebca** [comment]
Mmm I'm not sure I understand the logic here. If a file is opened at the root and the node_modules folder is nested below, node_modules nested below shouldn't affect what's in their parent anyway from the get go. Isn't that what's implied all the time for node / frontend development? node_modules folder affects its peers and children, but not files located in the parent folders usually... 🤔 

So locating tailwind according to the current opened file works, but you also have to find a the config file too, no? 🤔 

Maybe I don't understand the logic. What would be the unpredictable results?

**Comment by rchl** [comment]
It looks like the server gets out of it way to find the tailwind config file and also node_modules so then I guess it would be OK to make this change.

With a project structure like:

```
.
├── README.md
├── aureliajs
│   ├── aurelia_project
│   ├── cypress
│   ├── cypress.config.js
│   ├── cypress.json
│   ├── favicon.ico
│   ├── index.html
│   ├── karma.conf.js
│   ├── node_modules
│   ├── package-lock.json
│   ├── package.json
│   ├── src
│   ├── tailwind.config.js
│   ├── tailwind.css
│   ├── tailwindcss-plugins
│   ├── test
│   └── tsconfig.json
├── editor.sublime-project
└── test.css
```

it appears to be able to both find the config file and tailwindcss from node_modules:

```
LSP-tailwindcss: Found Tailwind CSS config file: /Users/../lsp-tailwindcss-client-error/aureliajs/tailwind.config.js
LSP-tailwindcss: Loaded postcss v8.4.5: /Users/../lsp-tailwindcss-client-error/aureliajs/node_modules/postcss
LSP-tailwindcss: Loaded tailwindcss v3.0.2: /Users/../lsp-tailwindcss-client-error/aureliajs/node_modules/tailwindcss
```

**Comment by predragnikolic** [comment]
> What would be the unpredictable results?

@davidwebca given the following folder structure:
```
.
├── nested_folder
│   ├── index1.html
│   ├── node_modules
│   ├── package.json
│   └── tailwind.config.js
└── index2.html
```

With my first [fix](https://github.com/sublimelsp/LSP-tailwindcss/pull/30/commits/09758f2694dfbf15e1959478674c99858daf8357).
There are two cases:
1. someone can first open the `index1.html` - in this case the the resolve script will be able to find the tailwindcss dependecy and the server will be started.
2. someone can first open the `index2.html` - in this case the the resolve script wont be able to find the tailwindcss dependecy and the server wont be started.

**Comment by predragnikolic** [comment]
Can this be merged?


BTW I was also thinking, 
If someone still reports issues like this,
I will consider removing the `is_allowed_to_start` entirely and always start the LSP-tailwindcss server.
The server would be
https://github.com/sublimelsp/LSP-tailwindcss/blob/5c91856f2b255cd96252ddf92da2adb8167d9a32/plugin.py#L27-L48

I only added the `is_allowed_to_start` method, to return helpful error messages to the user...
but I guess it would be better if the server return a message to display the message to the user.
https://microsoft.github.io/language-server-protocol/specification#window_showMessage

**Review by rchl — APPROVED** [review]

**Pull request merged**
